Repository yiisoft/yii2-debug, pull requests merged in 2018-04, with the labels that each got.

#312 docs/guide-ja updated [ci skip]
  docs/guide-ja/README.md
  docs/guide-ja/installation.md
  docs/guide-ja/topics-creating-your-own-panels.md
Labels: type:docs

#314 Fixes #300: Fixed email files are not deleted by GC
  CHANGELOG.md
  src/LogTarget.php
  src/panels/MailPanel.php
Labels: type:bug

#316 prevent multiple lines in toolbar
  CHANGELOG.md
  src/assets/toolbar.css
Labels: type:enhancement
