Repository yiisoft/yii2-debug, pull requests merged in 2019-07, with the labels that each got.

#397 Fixes #379: Unable to find debug data tagged with ''.
  .travis.yml
  CHANGELOG.md
  src/controllers/DefaultController.php
Labels: type:enhancement

#398 Enh #390 Better serializer (incl. closures) by using opis/closure
  CHANGELOG.md
  composer.json
  src/LogTarget.php
  src/Panel.php
  src/controllers/DefaultController.php
  src/panels/DumpPanel.php
  src/panels/LogPanel.php
  tests/FlattenExceptionTest.php
Labels: status:ready for merge, type:enhancement

#399 Enh #392: $tracePathMappings
  CHANGELOG.md
  README.md
  src/Module.php
  src/Panel.php
  tests/PanelTest.php
Labels: status:ready for merge, type:enhancement

#400 Fix #380: Enhanced browser compatibility
  CHANGELOG.md
  src/DebugAsset.php
  src/assets/js/db.js
  src/assets/js/polyfill.min.js
  src/assets/js/timeline.js
  src/assets/js/toolbar.js
Labels: type:enhancement

#402 Fix #401 SPL object closure
  CHANGELOG.md
  src/LogTarget.php
  src/Panel.php
  src/panels/DumpPanel.php
  src/panels/LogPanel.php
  src/views/default/panels/dump/detail.php
Labels: type:bug
