Repository yiisoft/yii2-debug, pull requests merged in 2019-03, with the labels that each got.

#352 Fix panel display when mails fail to serialize.
  CHANGELOG.md
  src/panels/MailPanel.php
Labels: status:ready for merge, type:bug

#361 Resizable and configurable debug panel size
  CHANGELOG.md
  src/Module.php
  src/assets/css/toolbar.css
  src/assets/css/toolbar.css.map
  src/assets/js/toolbar.js
  src/assets/scss/toolbar.scss
  src/controllers/DefaultController.php
  src/views/default/toolbar.php
Labels: status:code review, type:enhancement

#363 Fix #354: pre-format cell values
  CHANGELOG.md
  src/assets/css/main.css
  src/assets/scss/main.scss
  src/views/default/panels/assets/detail.php
Labels: status:code review, type:bug

#362 If touch() fails, display a clear InvalidConfigException
  CHANGELOG.md
  src/LogTarget.php
Labels: status:ready for merge, type:bug

#364 Simplify isEnabled() check for AssetPanel and avoid throwing errors
  CHANGELOG.md
  src/panels/AssetPanel.php
Labels: status:ready for merge, type:bug

#368 Allow customizing the UrlRule class used to generate rules in bootstrap
  CHANGELOG.md
  src/Module.php
Labels: status:code review, type:bug

#367 Fix keyboard navigation when bar is collapsed/hidden
  CHANGELOG.md
  src/assets/js/toolbar.js
Labels: status:code review, type:bug

#365 Dynamic html view title #353
  CHANGELOG.md
  src/Module.php
  src/views/layouts/main.php
Labels: type:enhancement

#369 Delay attaching to View events until action takes place
  CHANGELOG.md
  src/Module.php
Labels: status:code review, type:bug

#370 Use viewport height instead of body height
  src/assets/.gitignore
  src/assets/css/toolbar.css
  src/assets/js/toolbar.js
  src/assets/scss/toolbar.scss
  src/views/default/toolbar.php
Labels: status:code review
